### ISSUE TITLE
Error 4058 by installing

### ISSUE THREAD

**Issue by georgev79** [mruiter/com.gledopto#46]
Hi there! 

I'm new here. Getting this error by installing:

Trace: [Error: ENOENT: no such file or directory, open 'D:\Download\com.gledopto-master\com.gledopto-master\drivers\Light.js\driver.compose.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'D:\\Download\\com.gledopto-master\\com.gledopto-master\\drivers\\Light.js\\driver.compose.json'
}
    at App.preprocess (C:\Users\[username]\AppData\Roaming\npm\node_modules\athom-cli\lib\App\index.js:209:17)
    at async App.install (C:\Users\[username]\AppData\Roaming\npm\node_modules\athom-cli\lib\App\index.js:135:7)
    at async Object.exports.handler (C:\Users\[username]\AppData\Roaming\npm\node_modules\athom-cli\bin\cmds\app\install.js:27:3)
Plugin `compose` did not finish:
ENOENT: no such file or directory, open 'D:\Download\com.gledopto-master\com.gledopto-master\drivers\Light.js\driver.compose.json'

Aborting.

Any idea?

**Comment by georgev79** [comment]
Solved: I've used athom instead of homey to install.
